import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const ggbatang = localFont({
  src: "./fonts/ggbatang_Bold.otf",
  weight: "700",
  style: "normal",
  variable: "--font-ggbatang",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${ggbatang.variable} antialiased`}>{children}</body>
    </html>
  );
}
